/// The Fates Narrative Event System
/// Nona The Ninth Youngest of the Fates
/// Writes Code and Generates sequential challenges for TheFates Quests
/// 08/01/24
/// by Levi Scully

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace TheFates
{
    /// <summary>
    /// This class is responsible for generating and managing the code required to simulate quest templates.
    /// </summary>
    public class NonaTheSpinner
    {
        #region Singleton Logic

        private static readonly Lazy<NonaTheSpinner> _instance = 
            new Lazy<NonaTheSpinner>(() => new NonaTheSpinner());

        public static NonaTheSpinner Instance => _instance.Value;

        // Private constructor prevents external 'new' calls
        private NonaTheSpinner()
        {

        }

        #endregion
        
        private string codePathThreadsOfFate;
        public string finalPath;
        
        public void WeaveFullQuestLine(QuestLine questLine)
        {
            StringBuilder sb = new StringBuilder();
            string className = "ThreadsOf" + GetSafeName(questLine.questLineName);
            
            
            // Use Path.Combine to handle OS-specific slashes correctly
            // And ensure the directory exists before we try to write to it
            string folderPath = Path.Combine(Application.dataPath, "TheFates", "QuestSystem" ,"QuestLines");
    
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }

            // Keep the folder path as the base
            codePathThreadsOfFate = folderPath;
            
            WeaveTapestry(questLine, className);
            
            
        }
        
        private void WriteToFile(string content, string filename)
        {
            
            // Ensure the filename has the extension
            if (!filename.EndsWith(".cs")) filename += ".cs";

            // Combine the directory path with the specific filename
            
            finalPath = Path.Combine(codePathThreadsOfFate, filename);

            try 
            {
                File.WriteAllText(finalPath, content);
                Debug.Log($"Successfully wove logic to: {finalPath}");
                
            }
            catch (System.Exception e) 
            {
                Debug.LogError($"Nona failed to write: {e.Message}");
            }
        }

        private void AppendFileHeader(StringBuilder sb, QuestLine questLine)
        {
            var fileHeader = new List<string>
            {
                "//==============================================================================",
                "// THE FATES NARRATIVE EVENT SYSTEM",
                "// Generated by: Nona The Spinner (The Ninth Youngest of the Fates)",
                "// Target QuestLine: " + questLine.questLineName,
                "// Timestamp: " + System.DateTime.Now.ToString("MM/dd/yyyy HH:mm:ss"),
                "//",
                "// [SYSTEM ARCHITECTURE]",
                "// This is the LOGIC LAYER. It orchestrates trial sequences and HCI flows.",
                "// It is synced via ID with the DATA LAYER (ScriptableObject assets).",
                "//",
                "// [WARNING: MANUAL OVERWRITE PROTECTION]",
                "// FatesKeeper will prevent re-weaving if this file exists to protect manual",
                "// logic changes (Coroutines, WaitTimes, etc.). To regenerate, delete this file.",
                "//=============================================================================="
            };

            AppendLines(sb, fileHeader);
        }

        private void AppendLines(StringBuilder sb, List<string> lines)
        {
            foreach (var line in lines)
            {
                sb.AppendLine(line);
            }
        }

        public bool VerifyInputParameters(string inputQuests, string inputStages)
        {
            return false;
        }

        public static List<string> TheMagic = new()
        {
            "using System.Collections;",
            "using System.IO;",
            "using System.Collections.Generic;",
            "using System.Linq;",
            "using UnityEngine;"
 

        };
        
        public string GetSafeName(string input)
        {
            // Removes spaces and special characters: "Collect Wool!" -> "CollectWool"
            return System.Text.RegularExpressions.Regex.Replace(input, @"[^a-zA-Z0-9]", "");
        }
        
        public void WeaveTapestry(QuestLine questLine, string classname)
        {
            
            string questname = GetSafeName(questLine.questLineName);
            StringBuilder sb = new StringBuilder();

            // Add file header to the StringBuilder
            AppendFileHeader(sb, questLine);

            // Append the initial structure and imports for the ThreadsOfFate class
            AppendLines(sb, TheMagic);
            
            List<string> ClassMagic = new()
            {
                "\nnamespace TheFates\n{",
                "      public class " + classname + " : UnchangingFate",
                "      {\n"
        
            };
            
            AppendLines(sb, ClassMagic);

            // Append code for functions declaring challenges for each quest and stage combination
            AppendLines(sb, WeaveQuestStageChallengeFunctionDeclarations(questLine));

            // Append the challenge processing logic for the quests
            AppendLines(sb, WeaveTheCrossRoadsChallenges(questLine));

            // Finalize the class by closing the curly braces
            AppendLines(sb, new List<string> { "", "      }", "}" });

            WriteToFile(sb.ToString(), classname);
        }
        
        public List<string> WeaveTheCrossRoadsChallenges(QuestLine questLine)
        {
            List<string> listOut = new()
            {
                
                "\n            public IEnumerator TheCrossRoads(Challenge challenge)",
                "            {",
               // "                   IEnumerator fatesGoldenThread;",
                "                   switch (challenge.GetChallengeID().x, challenge.GetChallengeID().y, challenge.GetChallengeID().z)",
                "                 {"
            };
            
            int questCount =  questLine.quests.Count;
            
            for (int i = 1; i < questCount + 1; i++)
            {
                for (int j = 1; j < questLine.quests[i - 1].stages.Count + 1; j++)
                {
                    for (int k = 1; k <= questLine.quests[i - 1].stages[j - 1].challenges.Count; k++)
                    {
                        string functionName = GetSafeName(questLine.quests[i - 1].stages[j - 1].challenges[k - 1].challengeName);
                        listOut.Add($"                 case({i - 1},{j - 1},{k - 1}):");
                        listOut.Add($"                   fatesGoldenThread = {questLine.questLineName + functionName}Setup();");
                        listOut.Add("                   break;");
                    }
                }
            }
            
            listOut.Add("                 }");
            listOut.Add("                  return fatesGoldenThread;");
            listOut.Add("            }");
            return listOut;
        }
        
        public List<string> WeaveQuestStageChallengeFunctionDeclarations(QuestLine questLine)
        {
            
            int questCount =  questLine.quests.Count;
            List<string> listOut = new List<string>();
            
            
            for (int i = 1; i < questCount + 1; i++)
            {
                for (int j = 1; j < questLine.quests[i - 1].stages.Count + 1; j++)
                {
                    for (int k = 1; k <= questLine.quests[i - 1].stages[j - 1].challenges.Count; k++)
                    {
                        string functionName = GetSafeName(questLine.quests[i - 1].stages[j - 1].challenges[k - 1].challengeName);
                        // Line 1: Function Header
                        listOut.Add($"            public IEnumerator {questLine.questLineName + functionName}Setup()");
                        listOut.Add("            {");
                        listOut.Add("                 yield return null; // Wait for logic...");
                        listOut.Add("            }");
                    }
                }
            }
            return listOut;
        }

    }
}
